### ISSUE TITLE
panic on OSX watching file in SMB mounted volume

### ISSUE THREAD

**Issue by fredcy** [cortesi/modd#22]
I get the following panic when I use modd with a "prep" rule to watch a file on an SMB volume. OSX 10.10.5, modd 0.3, go 1.6.

```
panic: unhandled error: notify.FSEventsInodeMetaMod|notify.FSEventsMustScanSubDirs|notify.FSEventsIsDir

goroutine 18 [running]:
panic(0x422e4e0, 0xc82008eec0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/cortesi/modd/vendor/github.com/rjeczalik/notify.(*watch).Dispatch(0xc820096580, 0xc820090ee0, 0x1, 0x1)
	/Users/fcy/go/src/github.com/cortesi/modd/vendor/github.com/rjeczalik/notify/watcher_fsevents.go:136 +0x54f
github.com/cortesi/modd/vendor/github.com/rjeczalik/notify.(*watch).Dispatch-fm(0xc820090ee0, 0x1, 0x1)
	/Users/fcy/go/src/github.com/cortesi/modd/vendor/github.com/rjeczalik/notify/watcher_fsevents.go:205 +0x3e
github.com/cortesi/modd/vendor/github.com/rjeczalik/notify.gostream(0x4c00090, 0x1, 0x1, 0x4a001d0, 0x47ff000, 0x47fe000)
	/Users/fcy/go/src/github.com/cortesi/modd/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:104 +0x11c
github.com/cortesi/modd/vendor/github.com/rjeczalik/notify._cgoexpwrap_b138320e5461_gostream(0x4c00090, 0x1, 0x1, 0x4a001d0, 0x47ff000, 0x47fe000)
	??:0 +0x53
github.com/cortesi/modd/vendor/github.com/rjeczalik/notify._Cfunc_CFRunLoopRun()
	??:0 +0x36
github.com/cortesi/modd/vendor/github.com/rjeczalik/notify.init.1.func1()
	/Users/fcy/go/src/github.com/cortesi/modd/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:68 +0x112
created by github.com/cortesi/modd/vendor/github.com/rjeczalik/notify.init.1
	/Users/fcy/go/src/github.com/cortesi/modd/vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:70 +0x48
```

**Comment by cortesi** [comment]
Interesting. This seems to be a bug in rjeczalik/notify, the file notification library modd uses. Would you mind reporting this as an issue there? I'll also keep this issue open here.

**Comment by cortesi** [comment]
I believe the panic has been fixed in a recent merge in rjeczalik/notify. I'll close this for now.
