### ISSUE TITLE
incompatible with Go 1.6 cgo/GC rules

### ISSUE THREAD

**Issue by josharian** [cortesi/modd#6]
See https://tip.golang.org/doc/go1.6#cgo for background.

Using Go 1.6rc2 with github.com/cortesi/modd immediately generates a panic from within this library. To reproduce:

* Use Go 1.6rc2.
* `go get -u github.com/cortesi/modd/cmd/modd`
* Write a file called `modd.conf` that contains `* {}`.
* Execute `modd`.

Result:

```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/rjeczalik/notify.(*stream).Start(0xc820012700, 0x0, 0x0)
	$GOPATH/src/github.com/rjeczalik/notify/watcher_fsevents_cgo.go:131 +0x270
github.com/rjeczalik/notify.(*fsevents).watch(0xc8200742c0, 0xc82000e7e0, 0x17, 0x100001b00, 0x0, 0x0)
	$GOPATH/src/github.com/rjeczalik/notify/watcher_fsevents.go:206 +0x313
github.com/rjeczalik/notify.(*fsevents).RecursiveWatch(0xc8200742c0, 0xc82000e7e0, 0x17, 0x1b0000001b00, 0x0, 0x0)
	$GOPATH/src/github.com/rjeczalik/notify/watcher_fsevents.go:258 +0x51
go.(*struct { github.com/rjeczalik/notify.watcher; github.com/rjeczalik/notify.recursiveWatcher }).RecursiveWatch(0xc820086140, 0xc82000e7e0, 0x17, 0xc800001b00, 0x0, 0x0)
	<autogenerated>:50 +0x7c
github.com/rjeczalik/notify.(*recursiveTree).Watch(0xc8200880a0, 0xc82000e7e0, 0x17, 0xc8200a86c0, 0xc82000aaa8, 0x1, 0x1, 0x0, 0x0)
	$GOPATH/src/github.com/rjeczalik/notify/tree_recursive.go:286 +0xad6
github.com/rjeczalik/notify.Watch(0xc82000aaa0, 0x5, 0xc8200a86c0, 0xc82000aaa8, 0x1, 0x1, 0x0, 0x0)
	$GOPATH/src/github.com/rjeczalik/notify/notify.go:64 +0x7d
github.com/cortesi/modd/watch.Watch(0xc82000e780, 0x2, 0x2, 0x5f5e100, 0xc8200a84e0, 0xc82000e780, 0x0, 0x0)
	$GOPATH/src/github.com/cortesi/modd/watch/watch.go:301 +0x145
github.com/cortesi/modd.runOnChan(0xc8200a84e0, 0x4383390, 0x4b002f0, 0xc820012600, 0xc82000e680, 0x4307bb0, 0xb, 0xc82004fdb8, 0x0, 0x0, ...)
	$GOPATH/src/github.com/cortesi/modd/modd.go:89 +0x4d6
github.com/cortesi/modd.Run(0x4b002f0, 0xc820012600, 0xc82000e680, 0x4307bb0, 0xb, 0xc82004fdb8, 0x0, 0x0, 0x4013277, 0x0, ...)
	$GOPATH/src/github.com/cortesi/modd/modd.go:141 +0xbe
main.main()
	$GOPATH/src/github.com/cortesi/modd/cmd/modd/main.go:102 +0x9a2
```

**Comment by josharian** [comment]
Oops. Meant to file this at github.com/rjeczalik/notify/.

**Comment by josharian** [comment]
Filed at https://github.com/rjeczalik/notify/issues/90. Sorry for the noise.

**Comment by cortesi** [comment]
No probs - thanks for reporting this! :)
